### PR TITLE
Eliminate the use of package context manipulation

### LINKED ISSUE #248: Sometimes auto-approval packages produced by PVS/PV get stuck
Here is one example:

```
      Commit:     7c9c3406d5e297146b87a9b4998d3f9ee3cd9c4f
      Directory:  kindnet
      Ref:        kindnet/v1
      Repo:       https://github.com/nephio-project/nephio-example-packages.git
    Type:         git
Events:
  Type     Reason       Age                 From                 Message
  ----     ------       ----                ----                 -------
  Warning  Error        16m                 approval-controller  error approving: cannot change approval from Draft to Published
  Normal   NotApproved  28s (x14 over 14m)  approval-controller  approval policy "initial" not met
```

In this case, I see a bunch of "flapping" in the content of the package revision resources (see attached file). This will cause its own problems...

[flapping.txt](https://github.com/nephio-project/nephio/files/11617380/flapping.txt)

### LINKED ISSUE #249: Sometimes clusterName is not applied correctly
After setting up the sandbox and adding a PVS to create four clusters, I get this:

```
ubuntu@nephio-r1-e2e:~$ kubectl get clusters
NAME             PHASE         AGE   VERSION
edge01-cluster   Provisioned   28m   v1.26.3
edge02           Provisioned   23m   v1.26.3
edge03-cluster   Provisioned   23m   v1.26.3
edge04           Provisioned   23m   v1.26.3
ubuntu@nephio-r1-e2e:~$ 
```

I suspect this has the same root cause as the flapping in #248 - it's probably due to our improper use of `packageContext` in PV. I am going to try updating our packages to avoid that and see if it fixes it.

### PR DESCRIPTION
**Pull request by johnbelamaric**
This removes all use of the package variant "package context" manipulation feature. This feature was ill-conceived and causes some issues.

Instead, this uses a new in-cluster resource called WorkloadCluster, which right now contains only the clusterName, but in the future may have a few other fields (like CIDRs perhaps). This resource lives in the "controlling" or "parent" package `nephio-workload-cluster`. The name we use when we clone that package becomes the name of the workload cluster, and it is used as the basis for the names of all the 4 or 5 "secondary" packages needed to realize the cluster. By putting this name in a real object rather than setting it in the packageContext, we avoid the "flapping" or "thrashing" that happens due to issues with package context described in https://github.com/GoogleContainerTools/kpt/issues/3973. 

The apply-replacements function is used in nephio-workload-cluster to propagate the name from package context to everywhere, including this new resource (note, "name" is an appropriate, intended use of package context). This resource then gets put into the mgmt cluster along with the PV resource themselves, which have been configured to inject this WorkloadCluster resource into the packages they create.

Note that this is *not* the same as ClusterContext, which has more detailed information about the CNI config of the cluster, though this resource - which is in input to the capi-cluster-kind package - can be used to help construct that.
Hopefully, this:

Partially fixes https://github.com/nephio-project/nephio/issues/248
Partially fixes https://github.com/nephio-project/nephio/issues/249

Still testing!

/hold

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Noticed this while testing: https://github.com/GoogleContainerTools/kpt/issues/3979

**Comment by johnbelamaric** [comment]
Found this too: https://github.com/GoogleContainerTools/kpt/issues/3980 - but not sure if it's a bug or not.

**Comment by johnbelamaric** [comment]
cc @henderiw

**Comment by henderiw** [comment]
Why are we having an injection in the cluster-pv and not in the other pv(s)?

**Comment by johnbelamaric** [comment]
Accidentally...will fix

**Comment by henderiw** [comment]
Do we need the WorkloadCluster also in the downstream packages to start with ?

**Comment by johnbelamaric** [comment]
> Do we need the WorkloadCluster also in the downstream packages to start with ?

We need it in those that vary based on cluster name: cluster-capi-kind, rootsync, repository. I added it there. repository is a little special because we also use it without injection.

Testing now. I don't think it fixes all the problems, but it fixes some. The "flapping" problem looks to be a deeper issue. My suspicion right now is that that is either with the way optimistic concurrency is being used in the Porch client, or within the Porch server itself (or some combination of the too).

**Comment by johnbelamaric** [comment]
/hold cancel

Ok, so, this reduces the noise but doesn't fix all the flakiness. Another step towards fixing flakiness will be https://github.com/nephio-project/nephio/issues/251. I will probably bump the default auto-approve delay up to 2m in the PR for that too (though once that is fixed I am not *sure* we need the delay).

**Comment by johnbelamaric** [comment]
If you want to try this out:
1. You can build a sandbox using my branch:
   ```
   gcloud compute instances create --machine-type e2-standard-8 \
                                  --boot-disk-size 200GB \
                                  --image-family=ubuntu-2204-lts \
                                  --image-project=ubuntu-os-cloud \
                                  --metadata=startup-script-url=https://raw.githubusercontent.com/johnbelamaric/nephio-test-infra/no-pkg-ctx/e2e/provision/gce_init.sh \
                                  nephio-r1-e2e
   ```
2. Manually register my repo (https://github.com/johnbelamaric/nephio-example-packages.git) using the UI (authentication "None", read-only, external blueprints).
3. Clone nephio-workload-package/v6 to mgmt repo with the cluster name (say, "test01"), and approve it.

**Pull request merged**
