### PR TITLE
Import gitea config scripts

### PR DESCRIPTION
**Pull request by electrocucaracha**
The GITEA_ADMIN_USERNAME and GITEA_ADMIN_PASSWORD environment variables defines the initial admin gitea user.

### CODE REVIEW

**Comment by henderiw** [comment]
@electrocucaracha I will do a parallel PR where I added some capabilities to install app.ini + create the initial user from a secret. it also uses Postgres/memcache as the default helm chart does. Basically I created the package from the helm chart.
I am open for how we go fwd here. just wanted to share some stuff I looked in as I agree app.ini and user should be automatically created. The secret I use in the repo controller to get access to the Gitea server.

**Comment by electrocucaracha** [comment]
I have generated this from the official helm chart. The way that I have generated was disabling storage (volumes) and databases. I haven't tested this yet,  that's why I've submitted it as a draft.

**Comment by henderiw** [comment]
as said I am happy either way but we need the secret I mentioned.
I tested the package I submitted but it does not mean this is the way fwd.

**Comment by electrocucaracha** [comment]
> as said I am happy either way but we need the secret I mentioned. I tested the package I submitted but it does not mean this is the way fwd.

I'm going to close this and do reviews on your PR.

**Pull request closed without merging**
