### PR TITLE
Add MetalLB package

### PR DESCRIPTION
**Pull request by electrocucaracha**
This package can be utilized to expose Gitea services, among others

### CODE REVIEW

**Comment by henderiw** [comment]
@electrocucaracha are you also creating a package for metalb SW package?

**Comment by electrocucaracha** [comment]
> @electrocucaracha are you also creating a package for metalb SW package?

This package contains the Metal LB k8s resources and a configuration, did I miss something?

**Comment by henderiw** [comment]
sorry overlooked this. Is it not better to split them Since I always believe it is better to have the base code separated from the config.

**Comment by electrocucaracha** [comment]
> sorry overlooked this. Is it not better to split them Since I always believe it is better to have the base code separated from the config.

yeah, even for [upgrading](https://github.com/nephio-project/nephio-example-packages/pull/22) them is easier. Anyway, I'm going to remove the configuration from there.

**Pull request merged**
