### PR TITLE
split kind cluster in template/real cluster

### PR DESCRIPTION
**Pull request by henderiw**
this PR splits the kind cluster in a template package and a cluster package which consumes the templates.
this PR fixes also a topologyFlag which was not set to true.

### CODE REVIEW

**Comment by electrocucaracha** [comment]
@henderiw I know that gives more flexibility in terms of customization but also requires more steps in terms of consumption, can you provide some use cases and advantages of this PR? Maybe this derserves more discussion.

**Comment by henderiw** [comment]
so the idea is to split templates and classes from the cluster. this gives less CR(s) to the api-server and reference them. this is the intention what capital tried to do I believe

**Comment by electrocucaracha** [comment]
I've tested this with the test-infra bootstrap role and it seems to work

/lgtm

**Comment by johnbelamaric** [comment]
Merged and tagged.

**Pull request merged**
