### PR TITLE
enabled specializers

### PR DESCRIPTION
**Pull request by henderiw**
Enables specialzers in the nephio controller package

### CODE REVIEW

**Comment by henderiw** [comment]
https://github.com/nephio-project/nephio/issues/229

**Comment by johnbelamaric** [comment]
Awesome. Can you add ENABLE_APPROVAL too? I forgot to do that in my PR.

**Comment by johnbelamaric** [comment]
Actually don't bother, I still need to add all the permissions and stuff, so I can do it then.

**Review by johnbelamaric — APPROVED** [review]
/approve 
/lgtm

**Pull request merged**
