### PR TITLE
Update multus pkg to latest

### PR DESCRIPTION
**Pull request by efiacor**
Multus pkg change to include recent updates to the yml

### CODE REVIEW

**Comment by electrocucaracha** [comment]
/lgtm

The only concern here is using an upstream version of Multus CNI.

**Comment by johnbelamaric** [comment]
> The only concern here is using an upstream version of Multus CNI.

Yeah, perhaps that's why we ran into the problem in the first place, because we didn't pin the image?

@efiacor can you look into updating this package to ping to a specific Multus release, instead of what we have today, which seems to float? Because this issue is breaking even v1.0.1 it seems.

**Comment by efiacor** [comment]
> > The only concern here is using an upstream version of Multus CNI.
> 
> Yeah, perhaps that's why we ran into the problem in the first place, because we didn't pin the image?
> 
> @efiacor can you look into updating this package to ping to a specific Multus release, instead of what we have today, which seems to float? Because this issue is breaking even v1.0.1 it seems.

Will do. I have posted on their slack to check when their next release is planned. Last one was 4 mnths ago.
I also need to add a "watch" permission on the ClusterRole once the image can be pinned.

**Comment by electrocucaracha** [comment]
I'm going to test the option to use stable configuration files with stable tags. Something like [this](https://github.com/electrocucaracha/nephio-example-packages/blob/update_versions/multus/multus-daemonset-thick.yml#L155). I'll let you know my findings.

**Comment by efiacor** [comment]
Reverted to earlier version and pinned the image

**Comment by electrocucaracha** [comment]
@johnbelamaric I think this version will work (I had some issues to run e2e using these changes), can we merge this and tag a new release version to the packages?

**Pull request merged**
